import { StudentData } from "./types";

export const dummyStudents: StudentData[] = [
  {
    id: "1",
    name: "Arun Kumar",
    registerNumber: "CIT2021001",
    department: "Computer Science",
    internalMarks: 85,
    attendance: 92,
    skills: { communication: 78, aptitude: 82, technical: 88 },
    problemSolving: { problemsSolved: 120, contestParticipation: 8, rating: 1650 },
    achievements: ["Smart India Hackathon Finalist", "Published research paper on ML"],
  },
  {
    id: "2",
    name: "Priya Sharma",
    registerNumber: "CIT2021002",
    department: "Computer Science",
    internalMarks: 72,
    attendance: 88,
    skills: { communication: 85, aptitude: 70, technical: 65 },
    problemSolving: { problemsSolved: 45, contestParticipation: 3, rating: 1200 },
    achievements: ["Best Paper Award at Tech Symposium"],
  },
  {
    id: "3",
    name: "Vikram Raj",
    registerNumber: "CIT2021003",
    department: "Information Technology",
    internalMarks: 55,
    attendance: 70,
    skills: { communication: 60, aptitude: 55, technical: 50 },
    problemSolving: { problemsSolved: 20, contestParticipation: 1, rating: 900 },
    achievements: [],
  },
  {
    id: "4",
    name: "Divya Lakshmi",
    registerNumber: "CIT2021004",
    department: "Electronics",
    internalMarks: 91,
    attendance: 96,
    skills: { communication: 90, aptitude: 88, technical: 92 },
    problemSolving: { problemsSolved: 200, contestParticipation: 15, rating: 1900 },
    achievements: ["Google Summer of Code", "ACM ICPC Regionalist", "Open source contributor"],
  },
  {
    id: "5",
    name: "Rahul Menon",
    registerNumber: "CIT2021005",
    department: "Mechanical",
    internalMarks: 62,
    attendance: 78,
    skills: { communication: 65, aptitude: 60, technical: 58 },
    problemSolving: { problemsSolved: 30, contestParticipation: 2, rating: 1050 },
    achievements: ["Robotics club lead"],
  },
];
